# Generated by Django 4.2.4 on 2023-12-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="type",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
